
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(100),password VARCHAR(255));
CREATE TABLE roles(id INT AUTO_INCREMENT PRIMARY KEY,role_name VARCHAR(50));
CREATE TABLE user_roles(user_id INT,role_id INT);
CREATE TABLE posts(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,title VARCHAR(255),image VARCHAR(255));
